"""Generate ``seed_fx_rates.sql`` — daily USD/KRW/EUR rates from 2022-01-01.

Pulls the Frankfurter (ECB) timeseries for each base currency in one request
per base, then forward-fills missing dates (ECB only publishes on business
days) so every calendar day between START_DATE and END_DATE has a row.

Output schema:
    INSERT IGNORE INTO fx_rate_snapshots (base_currency, quote_currency, rate, recorded_at)
        VALUES (...), (...), ...;
    INSERT INTO fx_rates (...) VALUES (...) ON DUPLICATE KEY UPDATE rate=VALUES(rate), ...;

Re-runnable: each run regenerates the SQL file. ``INSERT IGNORE`` makes
the script idempotent against a partially-seeded DB. To extend the range,
just bump ``END_DATE`` and re-run.

Usage:
    cd backend && uv run python scripts/generate_fx_seed.py
"""

from __future__ import annotations

import json
import sys
import urllib.error
import urllib.request
from datetime import UTC, date, datetime, timedelta
from decimal import Decimal
from pathlib import Path

CURRENCIES: list[str] = ["USD", "KRW", "EUR"]
START_DATE: date = date(2022, 1, 1)
END_DATE: date = date.today()

OUTPUT_PATH: Path = Path(__file__).parent / "seed_fx_rates.sql"
FRANKFURTER_BASE: str = "https://api.frankfurter.app"


def fetch_timeseries(base: str, quotes: list[str]) -> dict[date, dict[str, Decimal]]:
    """Return {date: {quote: rate}} for every business day in the range."""
    to_param = ",".join(quotes)
    url = (
        f"{FRANKFURTER_BASE}/{START_DATE.isoformat()}..{END_DATE.isoformat()}"
        f"?from={base}&to={to_param}"
    )
    print(f"  GET {url}", file=sys.stderr)
    req = urllib.request.Request(url, headers={"User-Agent": "assetlog-fx-seed/1.0"})
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            payload = json.loads(resp.read())
    except urllib.error.URLError as exc:
        raise RuntimeError(f"Frankfurter request failed for base={base}: {exc}") from exc

    rates_raw = payload.get("rates")
    if not isinstance(rates_raw, dict):
        raise RuntimeError(f"Unexpected Frankfurter payload for base={base}: missing rates")

    out: dict[date, dict[str, Decimal]] = {}
    for date_str, quote_map in rates_raw.items():
        d = date.fromisoformat(date_str)
        out[d] = {q: Decimal(str(quote_map[q])) for q in quotes if q in quote_map}
    return out


def forward_fill(
    series: dict[date, dict[str, Decimal]],
    quotes: list[str],
) -> dict[date, dict[str, Decimal]]:
    """Fill every calendar day in [START_DATE, END_DATE] using the last known rate."""
    filled: dict[date, dict[str, Decimal]] = {}
    last: dict[str, Decimal] = {}
    cursor = START_DATE
    one_day = timedelta(days=1)
    while cursor <= END_DATE:
        if cursor in series:
            for q in quotes:
                if q in series[cursor]:
                    last[q] = series[cursor][q]
        if all(q in last for q in quotes):
            filled[cursor] = {q: last[q] for q in quotes}
        cursor += one_day
    return filled


def format_decimal(value: Decimal) -> str:
    """Render with 8 dp to match the Numeric(20,8) column."""
    quantized = value.quantize(Decimal("0.00000001"))
    return format(quantized, "f")


def write_sql(
    history: dict[str, dict[date, dict[str, Decimal]]],
    output: Path,
) -> tuple[int, int]:
    """Emit INSERT statements. Returns (snapshot_rows, latest_rows)."""
    snapshot_rows: list[str] = []
    latest_rows: list[str] = []
    fetched_at_str = datetime.now(tz=UTC).strftime("%Y-%m-%d %H:%M:%S")

    # Use UTC midnight as the canonical recorded_at — historical lookups use
    # ``recorded_at <= at`` so an early-day timestamp is the safe choice.
    for base, by_date in history.items():
        latest_date = max(by_date.keys()) if by_date else None
        for d, quote_map in sorted(by_date.items()):
            recorded_at = f"{d.isoformat()} 00:00:00"
            for quote, rate in quote_map.items():
                snapshot_rows.append(
                    f"('{base}','{quote}',{format_decimal(rate)},'{recorded_at}')"
                )
            if d == latest_date:
                for quote, rate in quote_map.items():
                    latest_rows.append(
                        f"('{base}','{quote}',{format_decimal(rate)},'{fetched_at_str}')"
                    )

    header = (
        "-- AUTO-GENERATED by backend/scripts/generate_fx_seed.py — do not hand-edit.\n"
        f"-- Range: {START_DATE} → {END_DATE} ({(END_DATE - START_DATE).days + 1} days)\n"
        f"-- Pairs:  {len(CURRENCIES)} currencies × {len(CURRENCIES) - 1} quotes = "
        f"{len(CURRENCIES) * (len(CURRENCIES) - 1)} pairs/day\n"
        f"-- Source: Frankfurter API ({FRANKFURTER_BASE}) — ECB reference rates,\n"
        "--         business-day data forward-filled to every calendar day.\n"
        "-- Apply:  mysql ... < scripts/seed_fx_rates.sql\n\n"
    )

    lines: list[str] = [header]

    if snapshot_rows:
        # Chunk to keep individual statements under MySQL's max_allowed_packet
        # default of 64MB — 1,000 rows per statement is very safe.
        chunk = 1000
        for i in range(0, len(snapshot_rows), chunk):
            block = ",\n  ".join(snapshot_rows[i : i + chunk])
            lines.append(
                "INSERT IGNORE INTO fx_rate_snapshots "
                "(base_currency, quote_currency, rate, recorded_at) VALUES\n  "
                + block
                + ";\n\n"
            )

    if latest_rows:
        block = ",\n  ".join(latest_rows)
        lines.append(
            "INSERT INTO fx_rates (base_currency, quote_currency, rate, fetched_at) VALUES\n  "
            + block
            + "\nON DUPLICATE KEY UPDATE rate=VALUES(rate), fetched_at=VALUES(fetched_at);\n"
        )

    output.write_text("".join(lines), encoding="utf-8")
    return len(snapshot_rows), len(latest_rows)


def main() -> None:
    print(
        f"Fetching FX timeseries {START_DATE} → {END_DATE} "
        f"for {CURRENCIES} from Frankfurter…",
        file=sys.stderr,
    )
    history: dict[str, dict[date, dict[str, Decimal]]] = {}
    for base in CURRENCIES:
        quotes = [c for c in CURRENCIES if c != base]
        raw = fetch_timeseries(base, quotes)
        history[base] = forward_fill(raw, quotes)
        print(
            f"  base={base}: {len(raw)} business days → "
            f"{len(history[base])} calendar days (forward-filled)",
            file=sys.stderr,
        )

    snap_count, latest_count = write_sql(history, OUTPUT_PATH)
    print(
        f"\nWrote {OUTPUT_PATH.relative_to(Path.cwd())} "
        f"— {snap_count} snapshot rows + {latest_count} latest rows.",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
